### ISSUE TITLE
stuck at re-indexing

### ISSUE THREAD

**Issue by thob** [typora-community-plugin/typora-plugin-footnotes#1]
Works for a short text, now I used it for a rather long one with  ~ 12500 words. It's stuck at 
![2024-10-01_14-05](https://github.com/user-attachments/assets/41d0ecee-0ee3-40e6-b03a-408c48b1df09)

**Comment by plylrnsdy** [comment]
it looks like something wrong when it parses the markdown. You can update it and see what error be throwed.

**Comment by thob** [comment]
after updating it indicated a syntax error.
![2024-10-01_20-22](https://github.com/user-attachments/assets/d3884234-bf5d-4d66-b5a1-74c59d0b5085)
After it corrected it worked as expected. Only thing is the error message doesn't go away (except if I restart)
