### ISSUE TITLE
unclear behavior with duplicate footnotes

### ISSUE THREAD

**Issue by thob** [typora-community-plugin/typora-plugin-footnotes#2]
It takes only the first iteration of `5`, the other two `5` were erased and not re-indexed.
![2024-10-01_14-22](https://github.com/user-attachments/assets/9776b17f-bfb7-4c71-b791-3d37a39c9d74)

Ideally it overwrites the `5`s to `6` and `7` according to their position in the text

**Comment by plylrnsdy** [comment]
fix in 1.0.1

**Comment by thob** [comment]
still getting this awkard index. It should generate 8 footnotes actually instead of just 6, no?
![2024-10-01_20-25](https://github.com/user-attachments/assets/0f74da42-b9e5-4f76-8206-06c2d7a0da8b)

**Comment by plylrnsdy** [comment]
I do not understand. Can you put the **Sample Markdown** and **Expected Markdown** in the comments?

**Comment by thob** [comment]
Check this out, makes sense?
![2024-10-02_09-39](https://github.com/user-attachments/assets/60d07f24-c403-45ae-872c-c627400d2082)
This makes sense only if the Fn `⁵` themselves, in the text, are also numbered correctly `⁶ and ⁷` based on their positions.

**Comment by plylrnsdy** [comment]
Footnotes are not used like that. It uses to give readers more information.

```markdown
I use Typora[^1] everyday.

[^1]: It is a markdown editor. Website: https://typora.io
```

All same indexes will point to the same footnote

**Comment by thob** [comment]
Well, what I described happens only if you edit a document over and over again and you loose track of the numbering, so it's rather an error correction. I understand your use case, I think, though but it would not work for a scholarly paper, from my point of view.

**Comment by plylrnsdy** [comment]
That is a new feature. Now it will re-index the existent footnotes.

Maybe you want a new command:

- **"Re-index missing footnote definations by footnote markers"**
- **"Generate a new numerical footnote marker"**

Or you want **footnote marker autocomplete**?

**Comment by plylrnsdy** [comment]
Or you can use footnote defination nearby footnote marker:

```markdown
paragraph[^1]

[^1]: ...

paragraph[^2][^3]

[^2]: ...
[^3]: ...

paragraph more
```

After finished your note, you can run the command "Re-index numerical footnotes" to move all footnote definations to the end of Markdown.

**Comment by plylrnsdy** [comment]
1.1.0 is released! Now support footnote marker suggestion.

Need to update plugin core to 2.3.28.

**Comment by thob** [comment]
I think the marker suggestion is pretty helpful, I need to dig deeper into using it. Thanks
